# Generated by Django 2.2.7 on 2019-12-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191203_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
