# Generated by Django 2.2.7 on 2019-12-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
